/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify email address via token sent by email */
        get: operations["AuthController_verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password — sets auth cookies */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile */
        get: operations["AuthController_getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using the refreshToken cookie */
        post: operations["AuthController_refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initiate Google OAuth login — redirects to Google */
        get: operations["AuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback — handled automatically by Google */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout — revokes refresh token and clears cookies */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requisitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all requisitions for an organization */
        get: operations["RequisitionsController_findAll"];
        put?: never;
        /** Create a new purchase requisition */
        post: operations["RequisitionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requisitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single requisition by ID */
        get: operations["RequisitionsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a DRAFT requisition */
        delete: operations["RequisitionsController_remove"];
        options?: never;
        head?: never;
        /** Update a DRAFT requisition */
        patch: operations["RequisitionsController_update"];
        trace?: never;
    };
    "/requisitions/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a DRAFT requisition for approval */
        post: operations["RequisitionsController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requisitions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a submitted requisition */
        post: operations["RequisitionsController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requisitions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a submitted requisition */
        post: operations["RequisitionsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List purchase orders for an organization (buyer or supplier) */
        get: operations["PurchaseOrdersController_findAll"];
        put?: never;
        /** Create a purchase order from an approved requisition */
        post: operations["PurchaseOrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single purchase order */
        get: operations["PurchaseOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send PO to supplier — DRAFT → SENT */
        post: operations["PurchaseOrdersController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm PO receipt by supplier — SENT → CONFIRMED */
        post: operations["PurchaseOrdersController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a PO — only allowed before goods are received */
        post: operations["PurchaseOrdersController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goods-receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all receipts for a purchase order */
        get: operations["GoodsReceiptsController_findAll"];
        put?: never;
        /** Log a new goods receipt — triggers PO status recalculation */
        post: operations["GoodsReceiptsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goods-receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single goods receipt */
        get: operations["GoodsReceiptsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices for an organization (buyer or supplier view) */
        get: operations["InvoicesController_findAll"];
        put?: never;
        /** Create an invoice draft against a purchase order */
        post: operations["InvoicesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single invoice with match result */
        get: operations["InvoicesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a DRAFT invoice (supplier only) */
        patch: operations["InvoicesController_update"];
        trace?: never;
    };
    "/invoices/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit invoice — triggers 3-way match, auto-approves if matched */
        post: operations["InvoicesController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually approve an EXCEPTION invoice (AP / Finance role) */
        post: operations["InvoicesController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject an EXCEPTION invoice (AP / Finance role) */
        post: operations["InvoicesController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments for an organization (payer or payee) */
        get: operations["PaymentsController_findAll"];
        put?: never;
        /** Record a payment against an approved invoice — marks invoice PAID and closes PO when fully paid */
        post: operations["PaymentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single payment record */
        get: operations["PaymentsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a PENDING payment as FAILED — invoice remains APPROVED, retry with a new payment */
        patch: operations["PaymentsController_fail"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example SecurePass1! */
            password: string;
            /** @example SecurePass1! */
            confirmPassword: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
        };
        AuthSuccessResponseDto: {
            /** @example true */
            success: boolean;
            /** @example Operation completed successfully. */
            message?: string;
        };
        LoginWithPasswordDto: {
            /** @example user@example.com */
            email: string;
            /** @example SecurePass1! */
            password: string;
        };
        UserResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example user@example.com */
            email: string;
            /** @example John */
            firstName: Record<string, never> | null;
            /** @example Doe */
            lastName: Record<string, never> | null;
            /** @example https://example.com/avatar.jpg */
            picture: Record<string, never> | null;
        };
        CreateRequisitionItemDto: {
            /** @example MacBook Pro 14" */
            description: string;
            /** @example 2 */
            quantity: number;
            /** @example 1999.99 */
            unitPrice: number;
            /** @example Needed for the design team */
            notes?: string;
        };
        CreateRequisitionDto: {
            /** @example Q2 Equipment Purchase */
            title: string;
            /** @example Laptops for new design hires */
            description?: string;
            /** @example org-uuid */
            orgId: string;
            /**
             * @default USD
             * @example USD
             */
            currency: string;
            items: components["schemas"]["CreateRequisitionItemDto"][];
        };
        RequisitionItemResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example MacBook Pro 14" */
            description: string;
            /** @example 2 */
            quantity: number;
            /** @example 1999.99 */
            unitPrice: number;
            /** @example 3999.98 */
            totalPrice: number;
            /** @example USD */
            currency: string;
            /** @example Needed for the design team */
            notes: Record<string, never> | null;
        };
        RequisitionResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example Q2 Equipment Purchase */
            title: string;
            /** @example Laptops for the new design hires */
            description: Record<string, never> | null;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "SUBMITTED" | "APPROVED" | "REJECTED" | "ORDERED";
            /** @example 3999.98 */
            totalAmount: number;
            /** @example USD */
            currency: string;
            /** @example user-uuid */
            requestedBy: string;
            /** @example approver-uuid */
            approvedBy: Record<string, never> | null;
            /** @example 2026-04-01T00:00:00.000Z */
            approvedAt: Record<string, never> | null;
            /** @example Budget exceeded for this quarter */
            rejectedReason: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            updatedAt: string;
            items: components["schemas"]["RequisitionItemResponseDto"][];
        };
        UpdateRequisitionDto: {
            /** @example Updated Equipment Purchase */
            title?: string;
            /** @example Updated description */
            description?: string;
            items?: components["schemas"]["CreateRequisitionItemDto"][];
        };
        RejectRequisitionDto: {
            /** @example Budget exceeded for this quarter */
            rejectedReason: string;
        };
        CreatePurchaseOrderItemDto: {
            /** @example MacBook Pro 14" */
            description: string;
            /** @example 2 */
            quantity: number;
            /** @example 1999.99 */
            unitPrice: number;
        };
        CreatePurchaseOrderDto: {
            /**
             * @description Must reference an APPROVED purchase requisition
             * @example pr-uuid
             */
            requisitionId: string;
            /**
             * @description Buyer organization — used for actor resolution
             * @example buyer-org-uuid
             */
            buyerOrgId: string;
            /** @example supplier-org-uuid */
            supplierOrgId: string;
            /**
             * @description Expected delivery date (ISO 8601)
             * @example 2026-05-01
             */
            expectedDate?: string;
            /**
             * @default 0
             * @example 50
             */
            shippingAmount: number;
            /**
             * @default USD
             * @example USD
             */
            currency: string;
            /** @example Urgent — please deliver by end of month */
            notes?: string;
            items: components["schemas"]["CreatePurchaseOrderItemDto"][];
        };
        PurchaseOrderItemResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example MacBook Pro 14" */
            description: string;
            /** @example 2 */
            quantity: number;
            /** @example 1999.99 */
            unitPrice: number;
            /** @example 3999.98 */
            totalPrice: number;
            /** @example USD */
            currency: string;
        };
        PurchaseOrderResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example pr-uuid */
            requisitionId: Record<string, never> | null;
            /** @example buyer-org-uuid */
            buyerOrgId: string;
            /** @example supplier-org-uuid */
            supplierOrgId: string;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "SENT" | "CONFIRMED" | "PARTIALLY_RECEIVED" | "RECEIVED" | "INVOICED" | "CLOSED" | "CANCELLED";
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            orderDate: string;
            /** @example 2026-05-01T00:00:00.000Z */
            expectedDate: Record<string, never> | null;
            /** @example 3999.98 */
            subtotal: number;
            /** @example 50 */
            shippingAmount: number;
            /** @example 4049.98 */
            totalAmount: number;
            /** @example USD */
            currency: string;
            /** @example user-uuid */
            createdBy: string;
            /** @example approver-uuid */
            approvedBy: Record<string, never> | null;
            /** @example 2026-04-01T00:00:00.000Z */
            approvedAt: Record<string, never> | null;
            /** @example Urgent delivery requested */
            notes: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            updatedAt: string;
            items: components["schemas"]["PurchaseOrderItemResponseDto"][];
        };
        CreateGoodsReceiptItemDto: {
            /**
             * @description Links to a specific PO line item
             * @example poi-uuid
             */
            orderItemId?: string;
            /** @example MacBook Pro 14" */
            description: string;
            /**
             * @description Quantity from the PO (for reference)
             * @example 2
             */
            quantityOrdered: number;
            /**
             * @description What actually arrived — the authoritative figure
             * @example 2
             */
            quantityReceived: number;
            /** @example 1 unit arrived damaged and was rejected */
            notes?: string;
        };
        CreateGoodsReceiptDto: {
            /** @example po-uuid */
            orderId: string;
            /**
             * @description Buyer organization ID — used for actor resolution
             * @example buyer-org-uuid
             */
            orgId: string;
            /** @example Partial delivery — remaining items expected next week */
            notes?: string;
            items: components["schemas"]["CreateGoodsReceiptItemDto"][];
        };
        GoodsReceiptItemResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example poi-uuid */
            orderItemId: Record<string, never> | null;
            /** @example MacBook Pro 14" */
            description: string;
            /** @example 2 */
            quantityOrdered: number;
            /** @example 2 */
            quantityReceived: number;
            /** @example 1 unit arrived damaged */
            notes: Record<string, never> | null;
        };
        GoodsReceiptResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example po-uuid */
            orderId: string;
            /** @example user-uuid */
            receivedBy: string;
            /**
             * Format: date-time
             * @example 2026-04-01T10:00:00.000Z
             */
            receivedAt: string;
            /** @example Partial delivery — 2 of 5 boxes arrived */
            notes: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-01T10:00:00.000Z
             */
            createdAt: string;
            items: components["schemas"]["GoodsReceiptItemResponseDto"][];
        };
        CreateInvoiceItemDto: {
            /**
             * @description Links this line to a PO line item for 3-way matching
             * @example poi-uuid
             */
            orderItemId?: string;
            /** @example MacBook Pro 14" */
            description: string;
            /** @example 2 */
            quantity: number;
            /** @example 1999.99 */
            unitPrice: number;
            /**
             * @description Discount rate (0–1)
             * @default 0
             * @example 0.05
             */
            discountRate: number;
            /** @example Bulk discount applied */
            notes?: string;
        };
        CreateInvoiceDto: {
            /**
             * @description Purchase order being invoiced
             * @example po-uuid
             */
            orderId: string;
            /**
             * @description Supplier organization — actor must be a member
             * @example supplier-org-uuid
             */
            supplierOrgId: string;
            /** @example buyer-org-uuid */
            buyerOrgId: string;
            /**
             * @description Payment due date (ISO 8601)
             * @example 2026-05-15
             */
            dueDate: string;
            /**
             * @default USD
             * @example USD
             */
            currency: string;
            items: components["schemas"]["CreateInvoiceItemDto"][];
        };
        InvoiceItemResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example poi-uuid */
            orderItemId: Record<string, never> | null;
            /** @example MacBook Pro 14" */
            description: string;
            /** @example 2 */
            quantity: number;
            /** @example 1999.99 */
            unitPrice: number;
            /** @example 0.05 */
            discountRate: number;
            /** @example 199.99 */
            discountAmount: number;
            /** @example 3799.99 */
            totalPrice: number;
            /** @example USD */
            currency: string;
            /** @example Bulk discount applied */
            notes: Record<string, never> | null;
        };
        InvoiceResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "SUBMITTED" | "PENDING_MATCH" | "MATCHED" | "EXCEPTION" | "APPROVED" | "REJECTED" | "PAID";
            /** @example supplier-org-uuid */
            supplierOrgId: string;
            /** @example buyer-org-uuid */
            buyerOrgId: string;
            /** @example po-uuid */
            orderId: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            issueDate: string;
            /**
             * Format: date-time
             * @example 2026-05-15T00:00:00.000Z
             */
            dueDate: string;
            /** @example 2026-04-20T00:00:00.000Z */
            paidDate: Record<string, never> | null;
            /** @example 3999.98 */
            subtotal: number;
            /** @example 199.99 */
            discountAmount: number;
            /** @example 3799.99 */
            totalAmount: number;
            /** @example 0 */
            paidAmount: number;
            /** @example USD */
            currency: string;
            /**
             * @description Result of the 3-way match — populated after submission
             * @example All 2 line item(s) passed the 3-way match.
             */
            matchNotes: Record<string, never> | null;
            /** @example user-uuid */
            createdBy: string;
            /** @example approver-uuid */
            approvedBy: Record<string, never> | null;
            /** @example 2026-04-02T00:00:00.000Z */
            approvedAt: Record<string, never> | null;
            /** @example Unit price does not match contract */
            rejectedReason: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            updatedAt: string;
            items: components["schemas"]["InvoiceItemResponseDto"][];
        };
        UpdateInvoiceDto: {
            /**
             * @description Updated due date (ISO 8601)
             * @example 2026-06-01
             */
            dueDate?: string;
            /** @description Replaces all existing line items */
            items?: components["schemas"]["CreateInvoiceItemDto"][];
            /** @example Updated payment terms */
            notes?: string;
        };
        RejectInvoiceDto: {
            /** @example Unit price does not match agreed contract rate */
            rejectedReason: string;
        };
        CreatePaymentDto: {
            /** @example invoice-uuid */
            invoiceId: string;
            /**
             * @description Payer organization — actor must be a member with Finance role
             * @example buyer-org-uuid
             */
            payerOrgId: string;
            /** @example supplier-org-uuid */
            payeeOrgId: string;
            /** @example 3799.99 */
            amount: number;
            /** @example USD */
            currency: string;
            /**
             * @description Payment method: bank_transfer, check, wire, credit_card, cash
             * @example bank_transfer
             */
            method?: string;
            /** @example Wire ref: TXN-20260401-001 */
            notes?: string;
        };
        PaymentResponseDto: {
            /** @example clx1234abcd */
            id: string;
            /** @example invoice-uuid */
            invoiceId: Record<string, never> | null;
            /** @example buyer-org-uuid */
            payerOrgId: string;
            /** @example supplier-org-uuid */
            payeeOrgId: string;
            /** @example 3799.99 */
            amount: number;
            /** @example USD */
            currency: string;
            /**
             * @example SUCCESS
             * @enum {string}
             */
            status: "PENDING" | "SUCCESS" | "FAILED";
            /** @example bank_transfer */
            method: Record<string, never> | null;
            /** @example Wire ref: TXN-20260401-001 */
            notes: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-01T00:00:00.000Z
             */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Verification email sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponseDto"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query: {
                /** @description Email verification token */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponseDto"];
                };
            };
            /** @description Invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginWithPasswordDto"];
            };
        };
        responses: {
            /** @description Logged in, auth cookies set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponseDto"];
                };
            };
            /** @description Invalid credentials or unverified email */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New auth cookies set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponseDto"];
                };
            };
            /** @description Missing or invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google authorization page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to frontend with auth cookies set */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponseDto"];
                };
            };
            /** @description Missing refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_findAll: {
        parameters: {
            query: {
                /** @description Organization ID */
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of requisitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisitionResponseDto"][];
                };
            };
            /** @description Not a member of the organization */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequisitionDto"];
            };
        };
        responses: {
            /** @description Requisition created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisitionResponseDto"];
                };
            };
            /** @description Not a member of the organization */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_findOne: {
        parameters: {
            query: {
                /** @description Organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requisition found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisitionResponseDto"];
                };
            };
            /** @description Requisition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_remove: {
        parameters: {
            query: {
                /** @description Organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requisition deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requisition is not in DRAFT status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the requester can delete */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_update: {
        parameters: {
            query: {
                /** @description Organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequisitionDto"];
            };
        };
        responses: {
            /** @description Requisition updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisitionResponseDto"];
                };
            };
            /** @description Requisition is not in DRAFT status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the requester can edit */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_submit: {
        parameters: {
            query: {
                /** @description Organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requisition submitted (or auto-approved if below threshold) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisitionResponseDto"];
                };
            };
            /** @description Invalid transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the requester can submit */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_approve: {
        parameters: {
            query: {
                /** @description Organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requisition approved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisitionResponseDto"];
                };
            };
            /** @description Invalid transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role or self-approval not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequisitionsController_reject: {
        parameters: {
            query: {
                /** @description Organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequisitionDto"];
            };
        };
        responses: {
            /** @description Requisition rejected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisitionResponseDto"];
                };
            };
            /** @description Invalid transition or missing rejection reason */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role or self-rejection not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseOrdersController_findAll: {
        parameters: {
            query: {
                /** @description Buyer or supplier organization ID */
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of purchase orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderResponseDto"][];
                };
            };
            /** @description Not a member of the organization */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseOrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchaseOrderDto"];
            };
        };
        responses: {
            /** @description Purchase order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderResponseDto"];
                };
            };
            /** @description Requisition is not APPROVED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role — buyer roles required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseOrdersController_findOne: {
        parameters: {
            query: {
                /** @description Buyer or supplier organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchase order found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderResponseDto"];
                };
            };
            /** @description Purchase order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseOrdersController_send: {
        parameters: {
            query: {
                /** @description Buyer organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PO sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderResponseDto"];
                };
            };
            /** @description Invalid transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Buyer role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseOrdersController_confirm: {
        parameters: {
            query: {
                /** @description Supplier organization ID — must match the PO's supplierOrgId */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PO confirmed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderResponseDto"];
                };
            };
            /** @description Invalid transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Supplier role required or org mismatch */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseOrdersController_cancel: {
        parameters: {
            query: {
                /** @description Buyer organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PO cancelled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderResponseDto"];
                };
            };
            /** @description PO is past the cancellable state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Buyer role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoodsReceiptsController_findAll: {
        parameters: {
            query: {
                /** @description Purchase order ID */
                orderId: string;
                /** @description Buyer or supplier organization ID */
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of receipts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoodsReceiptResponseDto"][];
                };
            };
            /** @description Order not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoodsReceiptsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoodsReceiptDto"];
            };
        };
        responses: {
            /** @description Receipt logged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoodsReceiptResponseDto"];
                };
            };
            /** @description PO is not in a receivable state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Buyer receiver role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoodsReceiptsController_findOne: {
        parameters: {
            query: {
                /** @description Buyer or supplier organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receipt found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoodsReceiptResponseDto"];
                };
            };
            /** @description Receipt not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvoicesController_findAll: {
        parameters: {
            query: {
                /** @description Buyer or supplier organization ID */
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponseDto"][];
                };
            };
        };
    };
    InvoicesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvoiceDto"];
            };
        };
        responses: {
            /** @description Invoice created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description PO is not in an invoiceable state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Supplier role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvoicesController_findOne: {
        parameters: {
            query: {
                /** @description Buyer or supplier organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description Invoice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvoicesController_update: {
        parameters: {
            query: {
                /** @description Supplier organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInvoiceDto"];
            };
        };
        responses: {
            /** @description Invoice updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description Invoice is not in DRAFT status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the supplier can edit */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvoicesController_submit: {
        parameters: {
            query: {
                /** @description Supplier organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice submitted. Status is APPROVED (matched) or EXCEPTION (failed) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description Invalid state or invoiced amount exceeds PO total */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Supplier role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvoicesController_approve: {
        parameters: {
            query: {
                /** @description Buyer organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice approved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description Invoice is not in EXCEPTION status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description AP or Finance role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvoicesController_reject: {
        parameters: {
            query: {
                /** @description Buyer organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectInvoiceDto"];
            };
        };
        responses: {
            /** @description Invoice rejected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description Invoice is not in EXCEPTION status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description AP or Finance role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_findAll: {
        parameters: {
            query: {
                /** @description Payer or payee organization ID */
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of payments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseDto"][];
                };
            };
        };
    };
    PaymentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentDto"];
            };
        };
        responses: {
            /** @description Payment recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseDto"];
                };
            };
            /** @description Invoice not APPROVED, currency mismatch, or amount exceeds total */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Finance Manager role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_findOne: {
        parameters: {
            query: {
                /** @description Payer or payee organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseDto"];
                };
            };
            /** @description Payment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_fail: {
        parameters: {
            query: {
                /** @description Payer organization ID */
                orgId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment marked as failed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseDto"];
                };
            };
            /** @description Payment is not in PENDING status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Finance Manager role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
