import { z } from "zod";

/** Base schema for Project */
const ProjectBaseSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  name: z.string().min(1),
  description: z.string().optional(),
  color: z.string().optional(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

/**
 * Full Project schema.
 * Represents a fully-initialized, persisted Project.
 */
export const ProjectSchema = ProjectBaseSchema.refine(
  (p) => p.updatedAt >= p.createdAt,
  { message: "updatedAt cannot be before createdAt" },
);

export type Project = z.infer<typeof ProjectSchema>;

/**
 * Schema for creating a new Project.
 * Excludes fields that are generated by the domain.
 */
export const CreateProjectSchema = ProjectBaseSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export class ProjectEntity {
  private props: Project;

  /**
   * Private constructor ensures all Project instances
   * pass through validation and controlled creation paths.
   */
  private constructor(props: Project) {
    this.props = ProjectSchema.parse(props);
  }

  /**
   * Creates a brand-new Project.
   *
   * This method:
   * - validates external input
   * - generates identity and timestamps
   * - guarantees invariants for newly created Projects
   */
  static create(input: unknown): ProjectEntity {
    const data = CreateProjectSchema.parse(input);

    return new ProjectEntity({
      ...data,
      id: crypto.randomUUID(),
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  /**
   * Rehydrates a Project from persistence (e.g. database).
   *
   * No domain defaults are applied here — the data must
   * already represent a valid persisted Project.
   */
  static fromPersistence(input: unknown): ProjectEntity {
    const data = ProjectSchema.parse(input);
    return new ProjectEntity(data);
  }

  get id(): string {
    return this.props.id;
  }
  get userId(): string {
    return this.props.userId;
  }
  get name(): string {
    return this.props.name;
  }
  get description(): string | undefined {
    return this.props.description;
  }
  get color(): string | undefined {
    return this.props.color;
  }

  /**
   * Updates the project name.
   * Always refreshes `updatedAt`.
   */
  updateName(name: string): void {
    this.props.name = name;
    this.props.updatedAt = new Date();
  }

  /**
   * Updates the project description.
   * Empty strings are allowed but still meaningful.
   */
  updateDescription(description: string): void {
    this.props.description = description;
    this.props.updatedAt = new Date();
  }

  /**
   * Returns a plain object representation
   * suitable for persistence or serialization.
   */
  toJSON(): Project {
    return { ...this.props };
  }
}
