import { z } from "zod";

// Base schema: all fields
const UserBaseSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email(),
  name: z.string().min(1).optional(),
  preferredSessionDuration: z.number().min(1).max(180).default(25),
  createdAt: z.date(),
  updatedAt: z.date(),
});

/**
 * Full User schema.
 * Represents a fully-initialized, persisted User.
 */
export const UserSchema = UserBaseSchema.refine(
  (u) => u.updatedAt >= u.createdAt,
  { message: "updatedAt cannot be before createdAt" },
);

export type User = z.infer<typeof UserSchema>;

/**
 * Schema for creating a new User.
 * Excludes fields that must be generated by the domain itself.
 */
export const CreateUserSchema = UserBaseSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export class UserEntity {
  /**
   * Private constructor ensures that all Users are created
   * through controlled factory methods.
   *
   * The constructor is the last line of defense:
   * no invalid UserEntity can exist in memory.
   */
  private constructor(props: User) {
    this.props = UserSchema.parse(props);
  }

  private props: User;

  /**
   * Creates a brand-new User.
   *
   * This method:
   * - validates external input
   * - generates identity and timestamps
   * - guarantees domain invariants for new Users
   */
  static create(input: unknown): UserEntity {
    const data = CreateUserSchema.parse(input);

    return new UserEntity({
      ...data,
      id: crypto.randomUUID(),
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  /**
   * Rehydrates a User from persistence (e.g. database).
   *
   * No fields are generated here — the data must already
   * represent a valid, persisted User.
   */
  static fromPersistence(input: unknown): UserEntity {
    const data = UserSchema.parse(input);
    return new UserEntity(data);
  }

  get id(): string {
    return this.props.id;
  }
  get email(): string {
    return this.props.email;
  }
  get name(): string | undefined {
    return this.props.name;
  }
  get preferredSessionDuration(): number {
    return this.props.preferredSessionDuration;
  }

  /**
   * Updates the user's name and refreshes `updatedAt`.
   * Centralizes mutation logic to preserve invariants.
   */
  updateName(name: string): void {
    this.props.name = name;
    this.props.updatedAt = new Date();
  }

  updatePreferredSessionDuration(duration: number): void {
    if (duration < 1 || duration > 180) {
      throw new Error("Session duration must be between 1 and 180 minutes");
    }
    this.props.preferredSessionDuration = duration;
    this.props.updatedAt = new Date();
  }

  /**
   * Returns a plain object representation.
   * Useful for serialization or persistence.
   */
  toJSON(): User {
    return { ...this.props };
  }
}
